

import React from 'react';

const PageSection: React.FC<{ title: string, children: React.ReactNode }> = ({ title, children }) => (
    <div className="mb-8">
        <h2 className="font-sora text-2xl font-bold text-white mb-3">{title}</h2>
        <div className="text-gray-400 leading-relaxed space-y-4">{children}</div>
    </div>
);

const PrivacyPage: React.FC = () => {
  return (
    <div className="bg-white/5 border border-white/10 rounded-2xl p-8 md:p-12 backdrop-blur-lg animate-fade-in">
      <h1 className="font-sora text-4xl md:text-5xl font-extrabold text-white mb-2">Privacy Policy</h1>
      <p className="text-gray-500 mb-10">Last updated: July 23, 2024</p>

      <PageSection title="Our Commitment to Your Privacy">
        <p>ContentJet AI is architected with world-class privacy and security as its foundation. We believe you should have complete control over your creative work and data. This policy outlines our minimalist approach to data handling and the robust measures we take to protect you. We are not just compliant; we are committed to being privacy-first.</p>
      </PageSection>

      <PageSection title="1. Information We Do NOT Collect or Store on Our Servers">
        <p>We want to be crystal clear about what we *don't* do. Our servers do not log, see, or store any of the following sensitive information:</p>
        <ul className="list-disc list-inside space-y-2 pl-4">
            <li>The content you enter as prompts (your "Input").</li>
            <li>The content generated by the AI (the "Output").</li>
            <li>Your Google Gemini API Key. This is a secret managed on the server-side and is never exposed to the client-side application or stored in logs.</li>
            <li>Any personal information like your name, email, or IP address. We do not have user accounts.</li>
        </ul>
      </PageSection>

      <PageSection title="2. Secure by Design: How Your Data is Processed">
        <p>When you generate content, your request is sent to a secure, isolated serverless function. This function acts as a fortified proxy, ensuring maximum security:</p>
         <ul className="list-disc list-inside space-y-2 pl-4">
            <li>It receives your anonymized request containing only the necessary data for generation (e.g., your prompt idea, platform, tone).</li>
            <li>It securely injects the secret API key on the server, never exposing it to the public internet or your browser.</li>
            <li>It communicates with the Google Gemini API over an encrypted connection.</li>
            <li>It streams the generated content directly back to your browser without ever writing it to a database or a permanent log file.</li>
        </ul>
        <p>All user-provided input is sanitized before processing to prevent injection attacks, and all AI-generated output is sanitized before being rendered in your browser to prevent Cross-Site Scripting (XSS) vulnerabilities.</p>
      </PageSection>
      
      <PageSection title="3. Your Data, Your Control: Browser Local Storage">
        <p>To provide a seamless, personalized experience (like saving your posts and settings), the application uses your browser's local storage. This data is stored **only on your computer**. It is never transmitted to, or stored on, our servers.</p>
        <p>You have the absolute right to view and delete this data at any time. You can clear all application data instantly and permanently from your browser by navigating to **Settings &gt; Data &amp; Privacy &gt; Clear All My Data** in the dashboard.</p>
      </PageSection>
      
       <PageSection title="4. Third-Party Services">
        <p>Our service uses the Google Gemini API. Your interactions with the AI are therefore also subject to the <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-accent-start hover:underline">Google Privacy Policy</a>. We encourage you to review their policy to understand how they handle data.</p>
      </PageSection>

      <PageSection title="5. Changes to This Policy">
        <p>We may update this Privacy Policy from time to time to reflect new features or security practices. We will notify you of any significant changes by posting the new policy on this page and updating the "Last updated" date. We encourage you to review this Privacy Policy periodically.</p>
      </PageSection>

      <PageSection title="6. Contact Us">
         <p>If you have any questions about our security and privacy practices, or if you are a security researcher and have found a potential vulnerability, please do not hesitate to contact us at <a href="mailto:hemaprabho37@gmail.com" className="text-accent-start hover:underline">hemaprabho37@gmail.com</a>.</p>
      </PageSection>
    </div>
  );
};

export default PrivacyPage;
