

import React from 'react';

const PageSection: React.FC<{ title: string, children: React.ReactNode }> = ({ title, children }) => (
    <div className="mb-8">
        <h2 className="font-sora text-2xl font-bold text-white mb-3">{title}</h2>
        <div className="text-gray-400 leading-relaxed space-y-4">{children}</div>
    </div>
);

const TermsPage: React.FC = () => {
  return (
    <div className="bg-white/5 border border-white/10 rounded-2xl p-8 md:p-12 backdrop-blur-lg animate-fade-in">
      <h1 className="font-sora text-4xl md:text-5xl font-extrabold text-white mb-2">Terms of Service</h1>
      <p className="text-gray-500 mb-10">Last updated: July 23, 2024</p>

      <PageSection title="1. Acceptance of Terms">
        <p>By accessing or using ContentJet AI ("the Service"), you signify your agreement to these Terms of Service ("Terms"). If you disagree with any part of the terms, then you do not have permission to access the Service. This agreement applies to all visitors, users, and others who wish to access or use the Service.</p>
      </PageSection>

      <PageSection title="2. Description of Service">
        <p>ContentJet AI is a software application that provides users with access to generative artificial intelligence models, specifically Google's Gemini API, to generate text-based content ("Output") based on user-provided text prompts ("Input"). The Service is a user interface and orchestration layer designed to simplify and enhance interaction with the underlying AI models.</p>
      </PageSection>

      <PageSection title="3. User Responsibilities & Conduct">
        <p>You are solely responsible for all your activity in connection with the Service. This includes the security and confidentiality of your API key (if applicable), the Input you provide, and your use of the Output.</p>
        <p>You agree not to use the Service for any purpose that is illegal, fraudulent, or harmful, or in connection with any unlawful, fraudulent, or harmful purpose or activity. You may not use the Service to generate content that is hateful, harassing, violent, or promotes discrimination against any individual or group.</p>
        <p><strong>ContentJet AI generates content for creative assistance. All responsibility for platform compliance, copyright, and content authenticity lies with the user. You are responsible for ensuring that the content you generate and publish complies with the terms of service of the respective platforms (e.g., Instagram, YouTube, etc.) and does not infringe on any third-party rights.</strong></p>
      </PageSection>

      <PageSection title="4. API Usage and Third-Party Services">
        <p>The core functionality of ContentJet AI relies on the Google Gemini API. Your use of this API through our Service is subject to Google's own terms of service, acceptable use policies, and privacy policies. ContentJet AI is not responsible for the availability, functionality, quality, or any costs that may be associated with your use of the Google Gemini API.</p>
      </PageSection>

      <PageSection title="5. Intellectual Property">
        <p><strong>Your Content:</strong> You retain all ownership rights to the Input you provide to the Service. Subject to the terms and policies of Google, you also own the rights to the Output generated for you. We claim no intellectual property rights over the content you create.</p>
        <p><strong>Our Content:</strong> We retain all rights, title, and interest in and to the Service itself, including all related intellectual property rights. This includes all aspects of our platform, such as the design, code, branding, and features. You may not duplicate, copy, or reuse any portion of the HTML/CSS, Javascript, or visual design elements without express written permission.</p>
      </PageSection>
      
      <PageSection title="6. Disclaimer of Warranties and Limitation of Liability">
        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. THE OUTPUT GENERATED BY THE AI IS FOR INFORMATIONAL PURPOSES ONLY AND WE DO NOT GUARANTEE ITS ACCURACY, COMPLETENESS, OR FITNESS FOR ANY PARTICULAR PURPOSE.</p>
        <p>IN NO EVENT SHALL CONTENTJET AI, ITS FOUNDER, OR ANY AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, OR OTHER INTANGIBLES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE OR YOUR RELIANCE ON ANY OUTPUT.</p>
      </PageSection>

      <PageSection title="7. Changes to Terms">
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. We will notify users by updating the "Last updated" date on this page.</p>
      </PageSection>
      
      <PageSection title="8. Contact Information">
         <p>If you have any questions about these Terms, please contact us at <a href="mailto:hemaprabho37@gmail.com" className="text-accent-start hover:underline">hemaprabho37@gmail.com</a>.</p>
      </PageSection>
    </div>
  );
};

export default TermsPage;
